export const adventures_ad_eng = 'Moments worth remembering for a lifetime. It can be snowshoeing in the deep snow where others can’t go. It can be e-biking in extreme winter in places you wouldn’t dare cycling. It can be a simple day of hiking across fells to enjoy the magical colours of Lappish Autumn (ruska). It can be summer backpacking trip with amazing camp nights by the fire or you can take part in our stunning bike tours and before you know it, you have conquered the most northern place in Europe with nothing but bicycle. We can give you magical experiences through the adventures we know to be exceptional.'

export const adventures_ad_est = '<p>Meeldejäävad hetked kogu eluks! Looduses matkamine sobib igasse aastaaega. Talvel pääseb liikuma räätsade või suuskadega, muul ajal jalgsi või rattaga. Meie elamusmatkade valikust leiad matku, mis sobivad nii algajatele kui ka kogenud seiklejatele. Tule tee räätsadega esimesed jäljed puutumatul lumel või ühine meiega pikematel rattaretkedel läbi põhjamaa karge ilu. Meie matkast võib saada Sinu suurte seikluste algus!</p>'

export const skiing_ad_eng = '<p>Did you know that skiing not only lifts our spirits, but adjusting to colder temperatures can also strengthen the immune system! Glide your way through quiet forests, over snowy glades and slopes and taste the frosty tang of freedom.</p><p>Levi holds one of the largest networks of ski runs in Finland. Stretching over 230 kilometres and fit for both classic and skate skiing, Levi’s ski network is valued for its great diversity and scenic routes. Come and capture a memory worth remembering!</p>'

export const skiing_ad_est = '<p>Kas teadsid, et suusatades ei parane kõigest enesetunne, vaid karge talveilm aitab tugevdada ka immuunsüsteemi! Suuskadel libised mõnusalt ja kergelt üle lumiste lagendike, liugled glasuuritud suhkrunõlvadel ja tuiskad läbi vaiksete metsatukkade.</p><p>Levilt leiad ühe Soome suurima suusavõrgustiku: üle 230 kilomeetri korrastatud suusaradu nii uisu- kui ka klassikastiiliks. Eriti hinnatud on radade mitmekesisus, mis võimaldab nautida nii loodust kui ka panna end igati proovile.</p>'

export const snowshoeing_ad_eng = '<p>Put on a pair of snowshoes, journey into the heart of winter and explore the peaceful charm of the Lappish landscape. Snowshoes take you beyond well-trodden trails to crunch your way over untouched snow. Climb fells, cross bogs and lakes and breathe in the quiet joy of the Lappish wilderness.</p><p>Snowshoeing is safe and easy to do. It’s a great option for anyone who enjoys exercise and spending time in nature. No previous experience or complicated equipment required. Snowshoes are attached directly to your boots and snowshoeing poles will be provided upon request.</p>'

export const snowshoeing_ad_est = '<p>Astu Lapimaa imekaunisse südamesse ja avasta talvemaastiku maagilisi radu. Lumeräätsadel rännates saad hõlpsasti kõndida ka sügavas lumes ja nautida iga sammu krõmpsuvat võlu. Matka tundrutel, ületa rabasid ja järvi ning tunne liikumisrõõmu.</p><p>Räätsadel on lihtne ja turvaline kõndida. Räätsamatk sobib kõigile, kes naudivad loodust ja liikumist, ega nõua matkajalt erilisi oskusi või varustust. Räätsad kinnitatakse matkaja saabaste külge ja soovi korral saab abiks ka matkakepid.</p>'
