export const GET_POST = 'GET_POST'
export const GET_POSTS = 'GET_POSTS'
export const POST_ERROR = 'POST_ERROR'

export const GET_ALBUM = 'GET_ALBUM'
export const GET_ALBUMS = 'GET_ALBUMS'
export const ALBUM_ERROR = 'ALBUM_ERROR'

export const GET_ADVENTURE = 'GET_ADVENTURE'
export const GET_ADVENTURES = 'GET_ADVENTURES'
export const GET_ADVENTURES_BY_CATEGORY = 'GET_ADVENTURES_BY_CATEGORY'
export const ADVENTURE_ERROR = 'ADVENTURE_ERROR'
export const PAYMENT_ACCEPTED = 'PAYMENT_ACCEPTED'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const MESSAGE_ERROR = 'MESSAGE_ERROR'

export const GET_FEEDBACK = 'GET_FEEDBACK'
export const ADD_FEEDBACK = 'ADD_FEEDBACK'
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR'
